ExternalProject_Add(Assimp_Debug_Shared
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/source/assimp
  DOWNLOAD_COMMAND ""
  #GIT_REPOSITORY "https://github.com/alexaut/assimp"
  #GIT_TAG "d8ec83e6fa7b7daf5fd61f8660915c7e06ba5eaa"
  UPDATE_COMMAND ""
  CMAKE_ARGS -DCMAKE_BUILD_TYPE=Debug
             -DBUILD_SHARED_LIBS=ON
             -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF
             -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
             -DASSIMP_BUILD_TESTS=OFF
             -DASSIMP_BUILD_OBJ_IMPORTER=ON
             -DASSIMP_BUILD_FBX_IMPORTER=ON
             -DASSIMP_BUILD_COLLADA_IMPORTER=ON
             -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_SOURCE_DIR}/bin/${CMAKE_SYSTEM_NAME}
             -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
             ${OS_ARGS}
)

ExternalProject_Add(Assimp_Release_Shared
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/source/assimp
  DOWNLOAD_COMMAND ""
  UPDATE_COMMAND ""
  CMAKE_ARGS -DCMAKE_BUILD_TYPE=Release
             -DBUILD_SHARED_LIBS=ON
             -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF
             -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
             -DASSIMP_BUILD_TESTS=OFF
             -DASSIMP_BUILD_OBJ_IMPORTER=ON
             -DASSIMP_BUILD_FBX_IMPORTER=ON
             -DASSIMP_BUILD_COLLADA_IMPORTER=ON
             -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_SOURCE_DIR}/bin/${CMAKE_SYSTEM_NAME}
             -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
             ${OS_ARGS}
)

ExternalProject_Add(Assimp_Debug_Static
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/source/assimp
  DOWNLOAD_COMMAND ""
  #GIT_REPOSITORY "https://github.com/alexaut/assimp"
  #GIT_TAG "d8ec83e6fa7b7daf5fd61f8660915c7e06ba5eaa"
  UPDATE_COMMAND ""
  CMAKE_ARGS -DCMAKE_BUILD_TYPE=Debug
             -DBUILD_SHARED_LIBS=OFF
             -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF
             -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
             -DASSIMP_BUILD_TESTS=OFF
             -DASSIMP_BUILD_OBJ_IMPORTER=ON
             -DASSIMP_BUILD_FBX_IMPORTER=ON
             -DASSIMP_BUILD_COLLADA_IMPORTER=ON
             -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_SOURCE_DIR}/bin/${CMAKE_SYSTEM_NAME}
             -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
             ${OS_ARGS}
)

ExternalProject_Add(Assimp_Release_Static
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/source/assimp
  DOWNLOAD_COMMAND ""
  UPDATE_COMMAND ""
  CMAKE_ARGS -DCMAKE_BUILD_TYPE=Release
             -DBUILD_SHARED_LIBS=OFF
             -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF
             -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
             -DASSIMP_BUILD_TESTS=OFF
             -DASSIMP_BUILD_OBJ_IMPORTER=ON
             -DASSIMP_BUILD_FBX_IMPORTER=ON
             -DASSIMP_BUILD_COLLADA_IMPORTER=ON
             -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_SOURCE_DIR}/bin/${CMAKE_SYSTEM_NAME}
             -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
             ${OS_ARGS}
)
