ExternalProject_Add(glm
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/source/glm
  #GIT_REPOSITORY "https://github.com/g-truc/glm"
  #GIT_TAG "fce2abd01ce21063bd25ba67c9318be83bf48813"
  DOWNLOAD_COMMAND ""
  UPDATE_COMMAND ""
  CMAKE_ARGS -DGLM_TEST_ENABLE=OFF
             -DBUILD_SHARED_LIBS=OFF
             -DBUILD_STATIC_LIBS=OFF
             -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_SOURCE_DIR}/bin/${CMAKE_SYSTEM_NAME}
             -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
             ${OS_ARGS}
)
